apiVersion: v1
kind: Service
metadata:
  name: clientes
  labels:
    app: clientes
spec:
  ports:
  - name: default
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: clientes
